const bcrypt = require('bcryptjs');
const db = require('./connection');
const { normalizeArabic } = require('../utils/arabicUtils');

function seedDatabase() {
  console.log('Seeding database with default users and realistic sample records...');

  // 1. Create Default Users if not exist
  const userCount = db.prepare('SELECT COUNT(*) as count FROM users').get().count;
  if (userCount === 0) {
    const salt = bcrypt.genSaltSync(10);
    const adminPass = bcrypt.hashSync('admin123', salt);
    const staffPass = bcrypt.hashSync('staff123', salt);

    const insertUser = db.prepare(`
      INSERT INTO users (username, password_hash, full_name, role)
      VALUES (?, ?, ?, ?)
    `);

    insertUser.run('admin', adminPass, 'مدير النظام - إدارة المدرسة', 'ADMIN');
    insertUser.run('staff', staffPass, 'موظف التسجيل والوثائق', 'STAFF');
    console.log('Default admin & staff accounts created.');
  }

  // 2. Check if students exist, if not insert sample students
  const studentCount = db.prepare('SELECT COUNT(*) as count FROM students').get().count;
  if (studentCount === 0) {
    const insertStudent = db.prepare(`
      INSERT INTO students (
        code, quad_name, normalized_name, surname, mother_name, dob, gender, nationality, religion,
        birth_place, province, district, sub_district, blood_type,
        id_type, id_number, national_id, record_number, page_number, family_number, id_issuer, id_issue_date,
        phone, alt_phone, email, city_village, neighborhood, mahalla, zuqaq, house_no, address_details, landmark, housing_type,
        emergency_contact_name, emergency_relationship, emergency_phone,
        has_special_needs, special_needs_type, special_needs_level, special_needs_details,
        grade, section, study_stage, study_type, admission_year, enrollment_year, previous_school, gpa, student_status,
        student_school_id, file_number, academic_notes,
        guardian_quad_name, guardian_relationship, guardian_phone, guardian_job, guardian_workplace, guardian_address
      ) VALUES (
        @code, @quad_name, @normalized_name, @surname, @mother_name, @dob, @gender, @nationality, @religion,
        @birth_place, @province, @district, @sub_district, @blood_type,
        @id_type, @id_number, @national_id, @record_number, @page_number, @family_number, @id_issuer, @id_issue_date,
        @phone, @alt_phone, @email, @city_village, @neighborhood, @mahalla, @zuqaq, @house_no, @address_details, @landmark, @housing_type,
        @emergency_contact_name, @emergency_relationship, @emergency_phone,
        @has_special_needs, @special_needs_type, @special_needs_level, @special_needs_details,
        @grade, @section, @study_stage, @study_type, @admission_year, @enrollment_year, @previous_school, @gpa, @student_status,
        @student_school_id, @file_number, @academic_notes,
        @guardian_quad_name, @guardian_relationship, @guardian_phone, @guardian_job, @guardian_workplace, @guardian_address
      )
    `);

    const sampleStudents = [
      {
        code: 'STU-000001',
        quad_name: 'مريم حيدر جواد كاظم',
        surname: 'الساعدي',
        mother_name: 'هدى رحيم جبار',
        dob: '2011-04-12',
        gender: 'أنثى',
        nationality: 'عراقية',
        religion: 'مسلم',
        birth_place: 'بغداد - الكرخ',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'المنصور',
        blood_type: 'O+',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '199834215687',
        national_id: '199834215687',
        record_number: '142',
        page_number: '88',
        family_number: '55412',
        id_issuer: 'أحوال المنصور',
        id_issue_date: '2020-02-15',
        phone: '07712345678',
        alt_phone: '07801234567',
        email: 'maryam.haidar@example.com',
        city_village: 'بغداد',
        neighborhood: 'اليرموك',
        mahalla: '612',
        zuqaq: '14',
        house_no: '22',
        address_details: 'بغداد - اليرموك - محلة 612 - زقاق 14 - دار 22',
        landmark: 'قرب جامع الشواف',
        housing_type: 'ملك',
        emergency_contact_name: 'حيدر جواد كاظم',
        emergency_relationship: 'الأب',
        emergency_phone: '07712345678',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        grade: 'الأول متوسط',
        section: 'أ',
        study_stage: 'المتوسطة',
        study_type: 'صباحي',
        admission_year: '2023',
        enrollment_year: '2023',
        previous_school: 'مدرسة بغداد الابتدائية للبنات',
        gpa: 98.5,
        student_status: 'مستمرة',
        student_school_id: '2023/101',
        file_number: 'F-2023-01',
        academic_notes: 'طالبة متميزة في مادة الرياضيات واللغة الإنجليزية',
        guardian_quad_name: 'حيدر جواد كاظم محمد',
        guardian_relationship: 'الأب',
        guardian_phone: '07712345678',
        guardian_job: 'مهندس اتصالات',
        guardian_workplace: 'وزارة الاتصالات',
        guardian_address: 'بغداد - اليرموك'
      },
      {
        code: 'STU-000002',
        quad_name: 'فاطمة علي حسين عبد الرضا',
        surname: 'التميمي',
        mother_name: 'زينب كريم عبد',
        dob: '2010-09-20',
        gender: 'أنثى',
        nationality: 'عراقية',
        religion: 'مسلم',
        birth_place: 'بغداد - الرصافة',
        province: 'بغداد',
        district: 'الرصافة',
        sub_district: 'الكرادة',
        blood_type: 'A+',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '200155443322',
        national_id: '200155443322',
        record_number: '310',
        page_number: '45',
        family_number: '78219',
        id_issuer: 'أحوال الكرادة',
        id_issue_date: '2021-06-10',
        phone: '07812345678',
        alt_phone: '07709876543',
        email: 'fatima.ali@example.com',
        city_village: 'بغداد',
        neighborhood: 'الكرادة الشرقية',
        mahalla: '903',
        zuqaq: '25',
        house_no: '8',
        address_details: 'بغداد - الكرادة الشرقية - محلة 903',
        landmark: 'قرب ساحة كهرمانة',
        housing_type: 'ملك',
        emergency_contact_name: 'علي حسين عبد الرضا',
        emergency_relationship: 'الأب',
        emergency_phone: '07812345678',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        grade: 'الثاني متوسط',
        section: 'ب',
        study_stage: 'المتوسطة',
        study_type: 'صباحي',
        admission_year: '2022',
        enrollment_year: '2022',
        previous_school: 'مدرسة المتفوقات الأولى للبنات',
        gpa: 99.2,
        student_status: 'مستمرة',
        student_school_id: '2022/105',
        file_number: 'F-2022-12',
        academic_notes: 'الأولى على المرحلة في العام السابق، مشاركة في أولمبياد العلوم',
        guardian_quad_name: 'علي حسين عبد الرضا جابر',
        guardian_relationship: 'الأب',
        guardian_phone: '07812345678',
        guardian_job: 'طبيب استشاري',
        guardian_workplace: 'مدينة الطب',
        guardian_address: 'بغداد - الكرادة الشرقية'
      },
      {
        code: 'STU-000003',
        quad_name: 'زينب مهدي صالح عمران',
        surname: 'الزبيدي',
        mother_name: 'إيمان صالح مهدي',
        dob: '2009-02-14',
        gender: 'أنثى',
        nationality: 'عراقية',
        religion: 'مسلم',
        birth_place: 'بغداد',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'حي الجامعة',
        blood_type: 'B+',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '200599887766',
        national_id: '200599887766',
        record_number: '89',
        page_number: '12',
        family_number: '43211',
        id_issuer: 'أحوال الكرخ',
        id_issue_date: '2019-11-04',
        phone: '07734567890',
        alt_phone: '',
        email: 'zainab.mahdi@example.com',
        city_village: 'بغداد',
        neighborhood: 'حي الجامعة',
        mahalla: '629',
        zuqaq: '33',
        house_no: '15',
        address_details: 'بغداد - حي الجامعة - شارع الربيع',
        landmark: 'قرب جامع ملا حويش',
        housing_type: 'ملك',
        emergency_contact_name: 'مهدي صالح عمران',
        emergency_relationship: 'الأب',
        emergency_phone: '07734567890',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        grade: 'الثالث متوسط',
        section: 'أ',
        study_stage: 'المتوسطة',
        study_type: 'صباحي',
        admission_year: '2021',
        enrollment_year: '2021',
        previous_school: 'مدرسة الرواد الابتدائية',
        gpa: 97.8,
        student_status: 'مستمرة',
        student_school_id: '2021/045',
        file_number: 'F-2021-08',
        academic_notes: 'متفوقة وموهوبة في الرسم والخط العربي',
        guardian_quad_name: 'مهدي صالح عمران خضير',
        guardian_relationship: 'الأب',
        guardian_phone: '07734567890',
        guardian_job: 'أستاذ جامعي',
        guardian_workplace: 'جامعة بغداد',
        guardian_address: 'بغداد - حي الجامعة'
      },
      {
        code: 'STU-000004',
        quad_name: 'نور الهدى قاسم جليل رحيم',
        surname: 'الخفاجي',
        mother_name: 'سعاد أحمد كريم',
        dob: '2008-07-30',
        gender: 'أنثى',
        nationality: 'عراقية',
        religion: 'مسلم',
        birth_place: 'بابل',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'الدورة',
        blood_type: 'AB+',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '200811223344',
        national_id: '200811223344',
        record_number: '205',
        page_number: '71',
        family_number: '65431',
        id_issuer: 'أحوال الدورة',
        id_issue_date: '2022-01-20',
        phone: '07501234567',
        alt_phone: '07802345678',
        email: 'noor.qasim@example.com',
        city_village: 'بغداد',
        neighborhood: 'حي الميكانيك',
        mahalla: '824',
        zuqaq: '19',
        house_no: '40',
        address_details: 'بغداد - الدورة - حي الميكانيك',
        landmark: 'قرب كنيسة مار بهنام',
        housing_type: 'إيجار',
        emergency_contact_name: 'قاسم جليل رحيم',
        emergency_relationship: 'الأب',
        emergency_phone: '07501234567',
        has_special_needs: 1,
        special_needs_type: 'ضعف بصر خفيف',
        special_needs_level: 'بسيط',
        special_needs_details: 'تستخدم نظارة طبية وتفضل الجلوس في المقاعد الأولى',
        grade: 'الرابع العلمي',
        section: 'أ',
        study_stage: 'الإعدادية',
        study_type: 'صباحي',
        admission_year: '2024',
        enrollment_year: '2024',
        previous_school: 'ثانوية المتفوقات',
        gpa: 96.0,
        student_status: 'مستمرة',
        student_school_id: '2024/011',
        file_number: 'F-2024-03',
        academic_notes: 'تحتاج مقعداً أمامياً لضعف البصر',
        guardian_quad_name: 'قاسم جليل رحيم سلمان',
        guardian_relationship: 'الأب',
        guardian_phone: '07501234567',
        guardian_job: 'موظف حكومي',
        guardian_workplace: 'وزارة النفط',
        guardian_address: 'بغداد - الدورة'
      },
      {
        code: 'STU-000005',
        quad_name: 'سارة عمار شاكر محمود',
        surname: 'الجنابي',
        mother_name: 'منى طارق صبحي',
        dob: '2007-11-18',
        gender: 'أنثى',
        nationality: 'عراقية',
        religion: 'مسلم',
        birth_place: 'بغداد',
        province: 'بغداد',
        district: 'الرصافة',
        sub_district: 'الأعظمية',
        blood_type: 'O-',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '200799112233',
        national_id: '200799112233',
        record_number: '411',
        page_number: '59',
        family_number: '31290',
        id_issuer: 'أحوال الأعظمية',
        id_issue_date: '2021-08-14',
        phone: '07706543210',
        alt_phone: '',
        email: 'sara.ammar@example.com',
        city_village: 'بغداد',
        neighborhood: 'سبع أبكار',
        mahalla: '314',
        zuqaq: '8',
        house_no: '12',
        address_details: 'بغداد - الأعظمية - سبع أبكار',
        landmark: 'قرب المعهد القضائي',
        housing_type: 'ملك',
        emergency_contact_name: 'عمار شاكر محمود',
        emergency_relationship: 'الأب',
        emergency_phone: '07706543210',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        grade: 'السادس العلمي',
        section: 'أ',
        study_stage: 'الإعدادية',
        study_type: 'صباحي',
        admission_year: '2022',
        enrollment_year: '2022',
        previous_school: 'مدرسة المتفوقات الأولى للبنات',
        gpa: 99.7,
        student_status: 'مستمرة',
        student_school_id: '2022/001',
        file_number: 'F-2022-01',
        academic_notes: 'مرشحة للمراتب الأولى على مستوى العراق في الامتحانات الوزارية',
        guardian_quad_name: 'عمار شاكر محمود عبد الله',
        guardian_relationship: 'الأب',
        guardian_phone: '07706543210',
        guardian_job: 'صيدلاني',
        guardian_workplace: 'مستشفى النعمان',
        guardian_address: 'بغداد - الأعظمية'
      }
    ];

    for (const stu of sampleStudents) {
      stu.normalized_name = normalizeArabic(stu.quad_name);
      insertStudent.run(stu);
    }
    console.log(`${sampleStudents.length} sample students created.`);
  }

  // 3. Check if teachers/staff exist, if not insert sample teachers
  const teacherCount = db.prepare('SELECT COUNT(*) as count FROM teachers_staff').get().count;
  if (teacherCount === 0) {
    const insertTeacher = db.prepare(`
      INSERT INTO teachers_staff (
        code, quad_name, normalized_name, surname, mother_name, dob, gender, nationality, religion, mother_tongue,
        birth_country, birth_place, province, district, sub_district, blood_type, social_status,
        id_type, id_number, national_id, record_number, page_number, family_number, id_issuer, issuer_country, id_issue_date,
        phone, alt_phone, email, city_village, neighborhood, mahalla, zuqaq, house_no, address_details, landmark, housing_type,
        emergency_contact_name, emergency_relationship, emergency_phone,
        has_special_needs, special_needs_type, special_needs_level, special_needs_details,
        employment_type, staff_category, employment_status, job_title, job_grade, classification, job_official_title, job_position,
        school_name, department, subject_taught, stages_taught, first_appointment_date, start_date, job_number, file_number,
        highest_degree, university, college_dept, specialization, grad_year, degree_name, training_courses, notes
      ) VALUES (
        @code, @quad_name, @normalized_name, @surname, @mother_name, @dob, @gender, @nationality, @religion, @mother_tongue,
        @birth_country, @birth_place, @province, @district, @sub_district, @blood_type, @social_status,
        @id_type, @id_number, @national_id, @record_number, @page_number, @family_number, @id_issuer, @issuer_country, @id_issue_date,
        @phone, @alt_phone, @email, @city_village, @neighborhood, @mahalla, @zuqaq, @house_no, @address_details, @landmark, @housing_type,
        @emergency_contact_name, @emergency_relationship, @emergency_phone,
        @has_special_needs, @special_needs_type, @special_needs_level, @special_needs_details,
        @employment_type, @staff_category, @employment_status, @job_title, @job_grade, @classification, @job_official_title, @job_position,
        @school_name, @department, @subject_taught, @stages_taught, @first_appointment_date, @start_date, @job_number, @file_number,
        @highest_degree, @university, @college_dept, @specialization, @grad_year, @degree_name, @training_courses, @notes
      )
    `);

    const sampleTeachers = [
      {
        code: 'TEA-000001',
        quad_name: 'سعاد عبد الكريم فاضل هاشم',
        surname: 'العبيدي',
        mother_name: 'بشرى صالح مهدي',
        dob: '1979-05-14',
        gender: 'أنثى',
        nationality: 'عراقي',
        religion: 'مسلم',
        mother_tongue: 'العربية',
        birth_country: 'العراق',
        birth_place: 'بغداد',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'المنصور',
        blood_type: 'A+',
        social_status: 'متزوج/ة',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '197944556677',
        national_id: '197944556677',
        record_number: '92',
        page_number: '18',
        family_number: '20934',
        id_issuer: 'أحوال الكرخ',
        issuer_country: 'العراق',
        id_issue_date: '2018-03-12',
        phone: '07701122334',
        alt_phone: '07801122334',
        email: 'suad.director@emis-school.iq',
        city_village: 'بغداد',
        neighborhood: 'الداوودي',
        mahalla: '611',
        zuqaq: '7',
        house_no: '19',
        address_details: 'بغداد - المنصور - الداوودي',
        landmark: 'قرب تقاطع الرواد',
        housing_type: 'ملك',
        emergency_contact_name: 'فاضل هاشم عبد',
        emergency_relationship: 'الزوج',
        emergency_phone: '07709988776',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        employment_type: 'ملاك دائم',
        staff_category: 'إداري',
        employment_status: 'مستمر',
        job_title: 'مديرة المدرسة',
        job_grade: 'الأولى',
        classification: 'مدرس',
        job_official_title: 'مدير أقدم',
        job_position: 'مدير',
        school_name: 'مدرسة المتفوقات الأولى للبنات',
        department: 'الإدارة المدرسية',
        subject_taught: 'إدارة تربوية / لغة عربية',
        stages_taught: 'إشراف عام',
        first_appointment_date: '2002-10-01',
        start_date: '2016-09-15',
        job_number: 'EMP-19042',
        file_number: 'T-001',
        highest_degree: 'ماجستير',
        university: 'جامعة بغداد - كلية التربية ابن رشد',
        college_dept: 'اللغة العربية',
        specialization: 'طرائق تدريس اللغة العربية',
        grad_year: '2001',
        degree_name: 'ماجستير في التربية',
        training_courses: 'دورة القيادة المدرسية الحديثة، دورة نظام EMIS الوزاري، دورة الذكاء الاصطناعي في التعليم',
        notes: 'حاصلة على شكر وتقدير من معالي وزير التربية لتميز الإدارة'
      },
      {
        code: 'TEA-000002',
        quad_name: 'رنا حسن عبد الخالق جبار',
        surname: 'المحمداوي',
        mother_name: 'نجاة كاظم محسن',
        dob: '1986-11-03',
        gender: 'أنثى',
        nationality: 'عراقي',
        religion: 'مسلم',
        mother_tongue: 'العربية',
        birth_country: 'العراق',
        birth_place: 'بغداد',
        province: 'بغداد',
        district: 'الرصافة',
        sub_district: 'زيونة',
        blood_type: 'O+',
        social_status: 'متزوج/ة',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '198622334455',
        national_id: '198622334455',
        record_number: '180',
        page_number: '34',
        family_number: '88123',
        id_issuer: 'أحوال الرصافة',
        issuer_country: 'العراق',
        id_issue_date: '2019-07-22',
        phone: '07805566778',
        alt_phone: '',
        email: 'rana.physics@emis-school.iq',
        city_village: 'بغداد',
        neighborhood: 'حي الغدير',
        mahalla: '702',
        zuqaq: '15',
        house_no: '30',
        address_details: 'بغداد - زيونة - قرب نادي اليرموك الترفيهي',
        landmark: 'قرب جامع القزازة',
        housing_type: 'ملك',
        emergency_contact_name: 'عبد الخالق جبار محمد',
        emergency_relationship: 'الأب',
        emergency_phone: '07805566779',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        employment_type: 'ملاك دائم',
        staff_category: 'تدريسي',
        employment_status: 'مستمر',
        job_title: 'مدرسة فيزياء',
        job_grade: 'الثانية',
        classification: 'مدرس',
        job_official_title: 'مدرس أول',
        job_position: 'مدرس',
        school_name: 'مدرسة المتفوقات الأولى للبنات',
        department: 'قسم العلوم الطبيعية',
        subject_taught: 'الفيزياء',
        stages_taught: 'الرابع والخامس والسادس العلمي',
        first_appointment_date: '2009-11-15',
        start_date: '2018-10-01',
        job_number: 'EMP-25410',
        file_number: 'T-042',
        highest_degree: 'بكالوريوس',
        university: 'جامعة النهرين - كلية العلوم',
        college_dept: 'قسم الفيزياء',
        specialization: 'فيزياء ذرية وليزر',
        grad_year: '2008',
        degree_name: 'بكالوريوس علوم فيزياء',
        training_courses: 'برامج المحاكاة الفيزيائية، إعداد المختبرات المدرسية الحديثة',
        notes: 'مشرفة نادي المبتكرين العلميين في المدرسة'
      },
      {
        code: 'TEA-000003',
        quad_name: 'خلود ماجد كاظم سلمان',
        surname: 'الشمري',
        mother_name: 'فوزية جاسم طه',
        dob: '1992-03-25',
        gender: 'أنثى',
        nationality: 'عراقي',
        religion: 'مسلم',
        mother_tongue: 'العربية',
        birth_country: 'العراق',
        birth_place: 'بغداد',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'حي العامل',
        blood_type: 'B+',
        social_status: 'أعزب/ة',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '199266778899',
        national_id: '199266778899',
        record_number: '74',
        page_number: '62',
        family_number: '44521',
        id_issuer: 'أحوال البياع',
        issuer_country: 'العراق',
        id_issue_date: '2020-09-10',
        phone: '07723344556',
        alt_phone: '',
        email: 'kholoud.math@emis-school.iq',
        city_village: 'بغداد',
        neighborhood: 'حي العامل',
        mahalla: '809',
        zuqaq: '21',
        house_no: '5',
        address_details: 'بغداد - حي العامل - شارع 7 نيسان',
        landmark: 'قرب ساحة 83',
        housing_type: 'ملك',
        emergency_contact_name: 'ماجد كاظم سلمان',
        emergency_relationship: 'الأب',
        emergency_phone: '07723344556',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        employment_type: 'ملاك دائم',
        staff_category: 'تدريسي',
        employment_status: 'مستمر',
        job_title: 'مدرسة رياضيات',
        job_grade: 'الرابعة',
        classification: 'مدرس',
        job_official_title: 'مدرس',
        job_position: 'مدرس',
        school_name: 'مدرسة المتفوقات الأولى للبنات',
        department: 'قسم الرياضيات',
        subject_taught: 'الرياضيات',
        stages_taught: 'الأول والثاني والثالث متوسط',
        first_appointment_date: '2016-12-01',
        start_date: '2020-09-01',
        job_number: 'EMP-31890',
        file_number: 'T-067',
        highest_degree: 'ماجستير',
        university: 'الجامعة المستنصرية - كلية التربية',
        college_dept: 'قسم الرياضيات',
        specialization: 'تحليل رياضي وجبر',
        grad_year: '2014',
        degree_name: 'ماجستير علوم رياضيات',
        training_courses: 'استراتيجيات حل المشكلات، تعليم التفكير الرياضي',
        notes: 'معدة منهاج التحدي للمتفوقات'
      },
      {
        code: 'TEA-000004',
        quad_name: 'وسن جاسم حميد عبيد',
        surname: 'السامرائي',
        mother_name: 'رجاء حميد عبد الله',
        dob: '1989-08-12',
        gender: 'أنثى',
        nationality: 'عراقي',
        religion: 'مسلم',
        mother_tongue: 'العربية',
        birth_country: 'العراق',
        birth_place: 'صلاح الدين',
        province: 'بغداد',
        district: 'الكرخ',
        sub_district: 'الغزالية',
        blood_type: 'AB-',
        social_status: 'متزوج/ة',
        id_type: 'بطاقة وطنية موحدة',
        id_number: '198977889900',
        national_id: '198977889900',
        record_number: '115',
        page_number: '50',
        family_number: '62134',
        id_issuer: 'أحوال الكرخ',
        issuer_country: 'العراق',
        id_issue_date: '2019-04-18',
        phone: '07508899001',
        alt_phone: '',
        email: 'wasan.records@emis-school.iq',
        city_village: 'بغداد',
        neighborhood: 'الغزالية',
        mahalla: '675',
        zuqaq: '12',
        house_no: '8',
        address_details: 'بغداد - الغزالية - قرب بدالة الغزالية',
        landmark: 'قرب جامع البديوي',
        housing_type: 'ملك',
        emergency_contact_name: 'جاسم حميد عبيد',
        emergency_relationship: 'الأب',
        emergency_phone: '07508899001',
        has_special_needs: 0,
        special_needs_type: '',
        special_needs_level: '',
        special_needs_details: '',
        employment_type: 'ملاك دائم',
        staff_category: 'إداري',
        employment_status: 'مستمر',
        job_title: 'مسؤولة شؤون الطلبة والتسجيل',
        job_grade: 'الثالثة',
        classification: 'موظف',
        job_official_title: 'مدقق وثائق أقدم',
        job_position: 'معاون',
        school_name: 'مدرسة المتفوقات الأولى للبنات',
        department: 'شعبة التسجيل والوثائق',
        subject_taught: 'إدارة وتوثيق',
        stages_taught: 'كافة المراحل',
        first_appointment_date: '2012-02-10',
        start_date: '2017-09-01',
        job_number: 'EMP-22019',
        file_number: 'T-015',
        highest_degree: 'بكالوريوس',
        university: 'جامعة بغداد - كلية الإدارة والاقتصاد',
        college_dept: 'قسم الإدارة العامة',
        specialization: 'إدارة المؤسسات التعليمية',
        grad_year: '2011',
        degree_name: 'بكالوريوس إدارة عامة',
        training_courses: 'نظام إدارة قواعد البيانات المدرسية، حفظ السجلات والتوثيق الإلكتروني',
        notes: 'مسؤولة عن تدقيق ملفات القبول الوزارية'
      }
    ];

    for (const tea of sampleTeachers) {
      tea.normalized_name = normalizeArabic(tea.quad_name);
      insertTeacher.run(tea);
    }
    console.log(`${sampleTeachers.length} sample teachers created.`);
  }

  console.log('Database seeding completed successfully.');
}

if (require.main === module) {
  seedDatabase();
}

module.exports = { seedDatabase };
